CHANGELOG.md
package.json
typescript/mocks/readTypeScriptModules/type-aliases.ts
typescript/processors/readTypeScriptModules.js
typescript/processors/readTypeScriptModules.spec.js

When aliasing a class one must create two declarations for a symbol:
```
class OriginalClass {}
const AliasedClass = OriginalClass;
type AliasedClass = OriginalClass;
```
Previously we were looking for the type on the value definition (i.e.
the `const`), and not finding it. Now if the type is not found on the
value definition then we search the other declarations for the first
to have a `type` property.
Related to https://github.com/angular/angular/pull/14523

fix(typescript): correctly extract the type definition from type aliases

---

jsdoc/index.js
jsdoc/processors/parse-tags.js
jsdoc/processors/parse-tags.spec.js
jsdoc/services/parser-adapters/backtick-parser-adapter.js
jsdoc/services/parser-adapters/backtick-parser-adapter.spec.js
jsdoc/services/parser-adapters/html-block-parser-adapter.js
jsdoc/services/parser-adapters/html-block-parser-adapter.spec.js

In markdown you can provide inline HTML blocks which
are not parsed for further markdown syntax.
In the same way that the parseTagsProcessor ignored potential
tags inside backtick code blocks, it now also ignores potential
tags inside inline HTML blocks. These blocks are identified with
the same semantic as inline HTML in markdown.
This fix is implemented by making the parser more generic and the
modifying its behaviour by specifying "parser adapters".
Currently parse adapters must expose the following interface:
```
interface ParseAdapter {
init(lines, tags);
nextLine(line, lineNumber)
parseForTags()
}
```
BREAKING CHANGE:
Tags inside HTML blocks are no longer parsed by default.
If you wish this to enable this then you can modify the
`parseTagsProcessor.parserAdapters` array from a …

fix(jsdoc): do not parse for tags within HTML blocks

---

typescript/mocks/readTypeScriptModules/spreadParams.ts
typescript/processors/readTypeScriptModules.js
typescript/processors/readTypeScriptModules.spec.js

The heavy-handed approach of stripping locally renamed
imports via regular expressions was breaking types
that legitimately contained dots.
The most common of these types that was being
broken was anonymous function types that used the
spread operator.
This change special cases such function types and
does not process them for local renames.
Closes #222

fix(typescript): ensure that function types are not clobbered

---

typescript/mocks/tsParser/getDecorators.test.ts
typescript/src/api-doc-types/ClassLikeExportDoc.ts
typescript/src/api-doc-types/MemberDoc.ts
typescript/src/services/TsParser/getDecorators.spec.ts
typescript/src/services/TsParser/getDecorators.ts

Closes #229
For tests see: #233

feat(typescript): Allow decorators to not be call expressions. 

---

typescript/mocks/readTypeScriptModules/gettersAndSetters.ts
typescript/src/api-doc-types/AccessorInfoDoc.ts
typescript/src/api-doc-types/ContainerExportDoc.ts
typescript/src/api-doc-types/PropertyMemberDoc.ts
typescript/src/processors/readTypeScriptModules/index.spec.ts
typescript/src/processors/readTypeScriptModules/index.ts

fix(typescript): handle property accessors correctly

---

jsdoc/services/code-name-matchers/export-default-declaration.js
jsdoc/services/code-name-matchers/export-default-declaration.spec.js
jsdoc/services/code-name-matchers/export-named-declaration.js
jsdoc/services/code-name-matchers/export-named-declaration.spec.js
jsdoc/services/code-name-matchers/index.js

I've encountered an unwanted warning when you use a named export:
```javascript
export function calc() {
doStuff();
}
```
Default exports were already supported so I figured it should be handled in the same way.

Added support for named exports

---

typescript/src/index.ts

fix(typescript): align default path and id templates

---

jsdoc/services/code-name-matchers/import-declaration.js
jsdoc/services/code-name-matchers/import-declaration.spec.js
jsdoc/services/code-name-matchers/index.js

A fix for #250 
By looking at https://astexplorer.net/ I think this is the best way to get a good enough name out of all import statements.
This matcher should return the following:
```javascript
import './file';                     // returns null
import foo from './file';            // returns foo
import { foo } from './file';        // returns foo
import { foo, bar } from './file';   // returns foo
```

Handle import

---

typescript/mocks/readTypeScriptModules/gettersAndSetters.ts
typescript/src/api-doc-types/PropertyMemberDoc.ts
typescript/src/processors/readTypeScriptModules/index.spec.ts

Right now, decorators of accessor properties will be only taken from the get accessor. This is not the expected behavior, because it can also happen that decorators are placed on the setter.

fix(typescript): fallback to decorators from set accessor

---

jsdoc/services/transforms/extract-type.spec.js

Removes an accidentally added debugger statement from 35763aafa89b85555ac122bcdd462f4452b1f51d

chore: remove debugger statement

---

typescript/src/services/TsParser/CustomCompilerHost.ts

* Currently the changes from https://github.com/angular/dgeni-packages/commit/b22dab5ba4d0f936e9bbf3e924f4894be28e503e do not work properly in a Windows environment. Due to the fact that the `this.baseDir` is already Posix normalized, using `path.sep` (which is `\` on windows) does always cause the base directory depth to be zero.
cc. @gregmagolan

fix(typescript): invalid path delimiter for triple slash type directives in windows

---

jsdoc/services/parser-adapters/html-block-parser-adapter.js
jsdoc/services/parser-adapters/html-block-parser-adapter.spec.js

The parser is designed to ignore tags inside
HTML blocks, but it did not understand these
less particular kinds of HTML tags.
Fixes https://github.com/angular/angular.js/issues/16671

fix(jsdoc): support void/self-closing/custom HTML tags

---

typescript/mocks/tsParser/multipleLeadingComments.ts
typescript/src/api-doc-types/AccessorInfoDoc.ts
typescript/src/api-doc-types/ApiDoc.ts
typescript/src/api-doc-types/ClassExportDoc.ts
typescript/src/api-doc-types/ClassLikeExportDoc.ts
typescript/src/api-doc-types/ConstExportDoc.ts
typescript/src/api-doc-types/ContainerExportDoc.ts
typescript/src/api-doc-types/EnumExportDoc.ts
typescript/src/api-doc-types/FunctionExportDoc.ts
typescript/src/api-doc-types/InterfaceExportDoc.ts
typescript/src/api-doc-types/MemberDoc.ts
typescript/src/api-doc-types/MethodMemberDoc.ts
typescript/src/api-doc-types/ModuleDoc.ts
typescript/src/api-doc-types/OverloadInfo.ts
typescript/src/api-doc-types/ParameterContainer.ts
typescript/src/api-doc-types/ParameterDoc.ts
typescript/src/api-doc-types/ParameterizedExportDoc.ts
typescript/src/api-doc-types/PropertyMemberDoc.ts
typescript/src/api-doc-types/TypeAliasExportDoc.ts
typescript/src/index.ts
typescript/src/processors/readTypeScriptModules/index.ts
typescript/src/services/TsParser/getContent.spec.ts
typescript/src/services/TsParser/getContent.ts
typescript/src/services/convertPrivateClassesToInterfaces.spec.ts
typescript/src/services/convertPrivateClassesToInterfaces.ts
typescript/src/services/ts-host/host.spec.ts
typescript/src/services/ts-host/host.ts

Introduces a new option that allows developers to configure the `tsHost` to not concatenate multiple leading comments for a `TypeScript` node content.
The `tsHost` is a newly created service that delegates (for now) to the `tsParser` package for retrieving the content of a given node. The advantage of the `tsHost` is that people can inject the `tsHost` in Dgeni `.config()` and specify options or overwrite methods.
Related angular/material2#12736.

feat(typescript): add option to disable leading comment concatenation

---

typescript/mocks/tsParser/multipleLeadingComments.ts
typescript/src/services/TsParser/getContent.spec.ts
typescript/src/services/TsParser/getContent.ts

* Due to bd748bb2867194e317e68d3331d0613a2bfafd97, calling `getContent` for a node which does not have any leading comment, leads to a runtime exception.

fix(typescript): do not throw if node does not have any comment

---

typescript/mocks/tsParser/getDeclarationTypeText.test.ts
typescript/src/services/TsParser/getDeclarationTypeText.spec.ts
typescript/src/services/TsParser/getDeclarationTypeText.ts

Where a declaration is an initializer and its value is a
new instance of a class, then display the type of that
class.

feat(typescript): improve declaration type text rendering

---

typescript/mocks/tsParser/multipleLeadingComments.ts
typescript/src/services/TsParser/getContent.spec.ts
typescript/src/services/TsParser/getContent.ts

In case the new `concatMultipleLeadingComments` is set to `false` and the first comment of a TypeScript node is a **single line** non-JSdoc comment, the node content will be empty.
This is because the first single line comment will taken as leading comment but then afterwards filtered because it doesn't start with `/**`.

fix(typescript): empty node description if first leading comment is single line trivia

---

typescript/mocks/tsParser/typeToString.ts
typescript/src/api-doc-types/ConstExportDoc.ts
typescript/src/services/ts-host/host.spec.ts
typescript/src/services/ts-host/host.ts

* Allows developers to specify type format flags in the `Host` class. This is useful if developers want to disable automatic `type` truncation for the `api-doc-types`.
**Note**: This change does only account for `typeToString` conversions in the API doc type classes. The `tsParser` instances are being left untouched.
cc. @petebacondarwin

feat(typescript): allow specifying type format flags for api-doc-types

---

typescript/mocks/readTypeScriptModules/methodParameters.ts
typescript/src/api-doc-types/ApiDoc.ts
typescript/src/api-doc-types/ConstExportDoc.ts
typescript/src/api-doc-types/ParameterDoc.ts
typescript/src/processors/mergeParameterInfo.spec.ts
typescript/src/processors/readTypeScriptModules/index.spec.ts
typescript/src/services/TsParser/getDeclarationTypeText.ts

Optional parameters that had not explicit type, but were initialized,
were not having their type computed correctly.
See https://github.com/angular/angular/issues/24355

fix(typescript): use correct optional parameter type

---

README.md

- some of the headers were not rendering properly
- this was because they included tabs instead of spaces
- removed a colon for consistency

docs(readme): fix headers

---

git/mocks/mocks.js
git/services/getPreviousVersions.js
git/services/getPreviousVersions.spec.js
git/services/versionInfo.js
git/services/versionInfo.spec.js
nunjucks/rendering/filters/marked.spec.js
nunjucks/services/renderMarkdown.spec.js
package.json
yarn.lock

The previous version of `marked` was vulnerable to a
[ReDoS](https://app.snyk.io/vuln/SNYK-JS-MARKED-174116)
attack.
BREAKING CHANGES
There are a few relevant breaking changes with this latest version of `marked`.
This only affects usage of the `renderMarkdown()` service and the `marked`
nunjucks filter. Take a look through the
[marked release notes](https://github.com/markedjs/marked/releases) and
check if this affects you.
Fixes #280

fix vulnerable dependencies

---

jsdoc/tag-defs/index.js
jsdoc/tag-defs/index.spec.js
jsdoc/tag-defs/version.js

Add support for jsdoc [@version tag](https://jsdoc.app/tags-version.html),

feat(jsdoc): add support for version tag

---

CHANGELOG.md

- the commit has important details about a breaking change but
it currently is a `404`

docs(changelog): fix broken link to important commit

---

jsdoc/services/jsParser-config.js
jsdoc/services/jsParser-config.spec.js

This would allow the usage of additional stuff such as the - nowadays widespread - async keyword.
I verified this in a local setup.
#312

Update ecmaVersion to 8

---

ngdoc/rendering/filters/link.js
ngdoc/rendering/filters/link.spec.js

Previously, when the `title` argument passed to the `link` filter was `undefined`, it would be stringified and included in the returned `@link` annotation (for example, `'{@link some/url undefined }'`). This would result in the string `'undefined'` being used as the link's text: `<a href="some/url">undefined</a>`.
This commit fixes the `link` filter behavior to omit the `title` when it is `undefined`. This results in `@link` annotations that do not include a "title" part (for example, `{@link some/url  }`), which in turn allows the link text to be inferred based on the URL.
NOTE:
This was accidentally broken in [commit 32d3b9bcd][1] by switching from lodash's `_.template()` (which treats undefined properties as empty strings) to a template literal (which stringifies undefined arguments). …

fix(ngdoc/link filter): correctly handle missing title

---

package.json
post-process-html/src/processors/postProcessHtml.ts
typescript/mocks/readTypeScriptModules/imports.ts
typescript/src/api-doc-types/ClassLikeExportDoc.ts
typescript/src/api-doc-types/ModuleDoc.ts
typescript/src/processors/readTypeScriptModules/index.spec.ts
typescript/src/services/TsParser/CustomCompilerHost.spec.ts
typescript/src/services/TsParser/CustomCompilerHost.ts
typescript/src/services/TsParser/FileInfo.ts
typescript/src/services/TsParser/index.ts
yarn.lock

This PR updates the `typescript` dependency to v4.5.4 (to take advantage of newer features and fix issues such as angular/angular#44468). See the individual commits for details.
##
This is a prerequisite for fixing angular/angular#44468.

build(deps): update `typescript` to v4.5.4

---

jsdoc/processors/extract-tags.js
jsdoc/processors/extract-tags.spec.js

Dgeni packages JSDoc does not support `@throws` by default (surprisingly
as a side note). Now if a project like Angular Material uses that somewhere,
the `Tag` will be instantiated without a `tagDef` because there is none.
Later after parsing (when the `Tag` was created), the extract tags processor
will log an error for such tags. This logic does not work as expected currently
because such `Tag` instances do not necessarily have the `errors` field, resulting
in runtime exceptions like:
```js
TypeError: Error running processor "extractTagsProcessor":
Cannot read properties of undefined (reading 'forEach')
at /private/var/tmp/_bazel_paul/24d3819ba30ba6e17ef227c181228208/sandbox/darwin-sandbox/4/execroot/angular_material/bazel-out/host/bin/tools/dgeni/dgeni.sh.runfiles/npm/node_modules/dgeni- …
```

fix(jsdoc): runtime error when jsdoc uses unknown tag definition

---

typescript/src/services/TsParser/getDecorators.ts

In TypeScript 4.8 the node's decorators are inside the `modifiers` array, instead of in a separate `decorators` array. These changes add some code to account for the difference while maintaining backwards compatibility.

fix(typescript): account for breaking change in TypeScript 4.8
